markdown: kramdown
permalink: /posts/:title
timezone: America/New York
  
plugins:
  - jekyll-seo-tag

gems:
  - jekyll-sitemap
  - jekyll-feed

name: Birch Well
url: http://birchwell.github.io
description: A storehouse for useful CLI commands, scripts, and Thunar Custom Actions.
